// src/snovy/list/List.svelte
<script lang="ts">

  import ListItem from "./ListItem.svelte"
  import type {CustomizableChild, ListPresets} from "../snovy-types"
  import {useMultiSelect} from "../../util/svelte-hooks"
  import type {GenericItem} from "../../util/types"
  import type {KeyMapping} from "../../util/utils"
  import {areArrayContentsIdentical, isArray} from "../../util/utils"
  import {Key} from "ts-key-enum"
  import {useKey} from "../../util/utils.js"

  type T = $$Generic<GenericItem>

  export let preset: ListPresets = "simple"
  export let custom: CustomizableChild

  export let items: Array<T> = []
  export let itemSort: (a: T, B: T) => number = undefined
  export let selected: T | Array<T> = undefined
  export let defaultSelected: T
  export let onMultiSelect: (selected: Array<T>) => void
  export let onSelect: (active: T | undefined) => void
  export let onContext: (active: T | undefined) => void
  export let onItemValueChange: (str: string) => void
  export let onItemRemove: (item: T) => void

  const {selectedItems, handleItemClick, resetSelection} = useMultiSelect(itemSort ? items.sort(itemSort) : items)

  const keyMap: Array<KeyMapping> = [
    {key: Key.Escape, handler: resetSelection}
  ]

  $: activeItem = $selectedItems.first()

  $: if (defaultSelected && !areArrayContentsIdentical($selectedItems, [defaultSelected])) {
    selectedItems.set([defaultSelected])
  }

  $: if (selected && isArray(selected) && !areArrayContentsIdentical($selectedItems, selected)) {
    selectedItems.set(selected)
  }

  $: if (isArray(selected)) {
    if (onMultiSelect && !areArrayContentsIdentical($selectedItems, selected)) {
      onMultiSelect($selectedItems)
    }

    if (onSelect && activeItem != selected?.first()) {
      console.log("select")
      onSelect(activeItem)
    }
  }

</script>

<ol {...$$restProps} class={`snovy-list snovy-scroll ${$$restProps.class || ""}`}
    tabIndex={-1} data-disabled={!items?.length} on:keydown={e => useKey(e, keyMap)}>
  {#each items as item (item.id)}
    <ListItem item={item} preset={preset} custom={custom}
              data-active={activeItem?.id === item.id} data-selected={$selectedItems.includes(item)}
              onValueChange={onItemValueChange}
              on:click={e => !e.defaultPrevented && handleItemClick(item)}
              on:contextmenu={e => e.stopPropagation() && onContext && onContext(item)}>
      <svelte:fragment slot="remove-button">
        {#if onItemRemove}
          <button on:click={e => {
            e.stopPropagation()
            onItemRemove(item)
          }}>
          </button>
        {/if}
      </svelte:fragment>
    </ListItem>
  {/each}
  <slot></slot>
</ol>

<style lang="scss">
  .snovy-list {
    position: relative;
    height: 100%;
    width: 100%;
    display: flex;
    flex-flow: column nowrap;
    align-items: flex-start;
    justify-content: flex-start;
    list-style: none;
    padding: 0;
    margin: 0;
  }
</style>

// src.snovy/component/snov/list/List.tsx
import React, {forwardRef, useEffect} from "react"
import ListItem from "./ListItem"
import {areArrayContentsIdentical, combineOptions, joinClass, KeyMapping, useKey} from "../../../util/utils"
import {Key} from "ts-key-enum"
import {useMultiSelect} from "../../../util/hooks"
import {CustomItem, GenericItem, UpdatableCustomItem} from "../../../util/types"
import {LIST} from "../../../util/classes"

export interface ListableProps<T extends GenericItem> extends Omit<React.HTMLProps<HTMLOListElement>, "onSelect" | "type" | "selected" | "label"> {
  items: Array<T> | undefined
  itemSort?: (a: T, B: T) => number
  onSelect?: (active: T | undefined) => void
  selected?: T | Array<T>
  customItem?: CustomItem<T>
  label?: { value: string, title?: string }
}

export type ListPresets = "simple" | "editable"

export type ListOptions = {
  readonly?: boolean
  useMultiSelect?: boolean
  preset?: ListPresets
}

const defaultOptions: ListOptions = {
  readonly: false,
  useMultiSelect: true,
  preset: undefined
}

//TODO arrow-key nav
//TODO on enter activate focused item
export interface ListProps<T extends GenericItem> extends ListableProps<T> {
  selected?: Array<T>
  defaultSelected?: T
  customItem?: UpdatableCustomItem<T>
  onMultiSelect?: (selected: Array<T>) => void
  onContext?: (active: T | undefined) => void
  onItemValueChange?: (str: string) => void
  onItemRemove?: (item: T) => void
  options?: ListOptions
}

//eslint-disable-next-line react/display-name
const ListWithRef = forwardRef(<T extends GenericItem>(
  {
    items,
    itemSort,
    selected,
    defaultSelected,
    onMultiSelect,
    onSelect,
    onContext,
    onItemValueChange,
    onItemRemove,
    options: passedOptions,
    customItem,
    children,
    className,
    ...props
  }: ListProps<T>,
  ref?: React.Ref<HTMLOListElement>
) => {

  const options = combineOptions(passedOptions, defaultOptions)

  const {
    activeItem,
    selectedItems,
    setSelectedItems,
    handleItemClick,
    resetSelection
  } = useMultiSelect<T>(items ? itemSort ? items?.sort(itemSort) : items : [])

  const keyMap: Array<KeyMapping> = [
    {key: Key.Escape, handler: resetSelection}
  ]

  useEffect(
    () => {
      defaultSelected && !areArrayContentsIdentical(selectedItems, [defaultSelected]) && setSelectedItems([defaultSelected])
    }, [defaultSelected]
  )

  useEffect(
    () => {
      selected && !areArrayContentsIdentical(selectedItems, selected) && setSelectedItems(selected)
    }, [selected]
  )

  useEffect(
    () => {
      onMultiSelect && !areArrayContentsIdentical(selectedItems, selected) && onMultiSelect(selectedItems)
      onSelect && activeItem != selected?.first() && onSelect(activeItem)
    }, [selectedItems]
  )

  return (
    <ol
      {...props} ref={ref} className={joinClass([LIST, "snovy-scroll", className])} tabIndex={-1}
      data-disabled={!items?.length} onKeyDown={e => useKey(e, keyMap)}
    >
      {
        items?.map((item, index) =>
          <ListItem
            key={`${index}-${item}`} item={item} preset={options.preset} customItem={customItem}
            onValueChange={onItemValueChange} onRemove={onItemRemove}
            selected={selectedItems.includes(item)} active={activeItem == item}
            onSelect={handleItemClick} onContext={onContext}
          />
        )
      }
      {children}
    </ol>
  )

})

const List = ListWithRef as <T extends GenericItem>(props: ListProps<T> & { ref?: React.Ref<HTMLOListElement> }) => JSX.Element
export default List
